name: Crear Cliente

on:
  workflow_dispatch:
    inputs:
      nombre:
        description: 'Nombre del cliente'
        required: true
      servicio:
        description: 'Tipo de servicio (TV, Internet, Telefonía)'
        required: true
      descripcion:
        description: 'Descripción del servicio contratado'
        required: true

permissions:
  contents: write  # Hace push de archivos generados

jobs:
  crear_cliente:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Ejecutar script para crear cliente
      run: |
        python app/main.py crear "${{ github.event.inputs.nombre }}" "${{ github.event.inputs.servicio }}" "${{ github.event.inputs.descripcion }}"

    - name: Mostrar contenido de la carpeta data/
      run: |
        echo "Contenido generado:"
        ls -la data/
        cat data/*.txt || echo "No hay archivos generados"

    - name: Hacer commit de los nuevos archivos
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/
        git commit -m "Cliente agregado automáticamente: ${{ github.event.inputs.nombre }}"
        git push
